#最大階層数
Max-Layer: 10
#初期層のスポーン位置(rank=1(初期層)のとき)
SpawnLocation:
  x: 0.5
  y: 4.0
  z: 0.5

#1階層増える毎にどれだけy座標を増加させるか？
y_gain: 0.0

#rank=1での半径R
R_0: 5.0

#1階層上がる毎のRの変化量
dR: 0.0

#時間制限[sec]
TimeLimit: 120

#1のとき:誰かが最上階に到達した段階で終了
Gamemode: 1
